### ISSUE TITLE
Need some packages of "util" and functions like "AutoComputedShelfDB"

### ISSUE THREAD

**Issue by lynhsiong** [cinquin/ChIP-GPT-llm#1]
Hello, I am very interested in your great work. However,  maybe you forgot to upload a util directory. The main python script of "ChipGPT.py" need to import a package of "util", which could contains many other functions or classes like "AutoComputedShelfDB", please have a check, thank you!

**Comment by cinquin** [comment]
Hi, thanks for your interest! I've added the missing file.
